[package]
name = "odroid-show"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
libc = "0.2.139"
libusb1-sys = "0.6.4"
